name: pr

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.16.3'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: build --snapshot --rm-dist
      - name: test
        run: |
          ls -la